---
dist: trusty
language: perl
perl:
  - "5.26.0"
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:longsleep/golang-backports'


before_install:
## Install SSL
  - sudo apt-get update
  - sudo apt-get install golang-go
  - sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev wget pkg-config rpm git 
    
  - export VERSION=3.1.1
  - wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz 
  - rpmbuild -tb singularity-${VERSION}.tar.gz
  - sudo rpm -ivh ~/rpmbuild/RPMS/x86_64/singularity-$VERSION-1.el7.x86_64.rpm
  - rm -rf ~/rpmbuild singularity-$VERSION*.tar.gz

## Install conda
##  - wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - wget https://repo.anaconda.com/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda activate base
  - conda config --set always_yes yes --set changeps1 no
#  - conda update -q conda
  - conda info -a

## Download cpan libraries
## For some reason DB_File installation fails, it is not needed for the test
  - sed -i '/DB_File/d' ./definitions/cpanfile
  - cd definitions; cpanm --quiet --notest --installdeps .
  - cd -
## Set up for cpanm dependencies test
  - cpanm --notest Devel::Cover::Report::Coveralls

install:
## Test installation script and gather coverage information
  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_install.test
## Generate rare disease installation script
  #- PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl mip install rd_dna --bash_set_errexit --install emip epeddy eperl5 epy3 esvdb etiddit --envn emip=mip_travis epeddy=mip_travis_peddy eperl5=mip_travis_perl5 epy3=mip_travis_py3 esvdb=mip_travis_svdb etiddit=mip_travis_tiddit --skip gatk --skip snpeff --skip cnvnator
## Install MIP rare disease
#- bash mip.sh
## Generate rna installation script
  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl mip install rd_rna --bash_set_errexit --install emip epy3 eperl5 
## Install MIP rna
  - bash mip.sh

script:
## Test MIP rd_dna
 # - conda activate mip_travis
## Set-up test coverage for test directory "t"
  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",+ignore,"prove",-coverage,statement,branch,condition,path,subroutine prove -lrs -j 9 t
### Download
## Set-up test coverage for mip_download_rd_dna.test
# - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_download_rd_dna.test
## Set-up test coverage for mip_download_rd_dna.test
#  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_download_rd_rna.test
### Analyse
## Set-up test coverage for mip_analyse_rd_dna.test
#  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_analyse_rd_dna.test
## Set-up test coverage for mip_analyse_vcf_rerun.test
#  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_analyse_rd_dna_vcf_rerun.test
## Set-up test coverage for mip qccollect
#  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_qccollect.test
## Set-up test coverage for mip vcfparser
#  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_vcfparser.test
## Set-up test coverage for mip_analyse_vcf_rerun.test
#  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_analyse_dragen_rd_dna.test
## Set-up test coverage for mip_analyse_rna.test
  - conda activate mip7_rd-rna
  - PERL5OPT=-MDevel::Cover=-ignore,"^t/",-coverage,statement,branch,condition,path,subroutine perl t/mip_analyse_rd_rna.test
## Get some coverage statistics
  - cover

after_success:
## Generate report for coveralls
  - cover -report coveralls
